### ISSUE TITLE
Where is the source code for automatic post-editing?

### ISSUE THREAD

**Issue by snailcoder** [eske/seq2seq#13]
I've read the paper LIG-CRIStAL System for the WMT17 Automatic Post-Editing Task. As the paper said, the code for automatic post-editing is at  https://github.com/eske/seq2seq/tree/APE. But it seems to be lost...

**Comment by eske** [comment]
Hello,

Indeed, the files have been moved to another location. You can find the source code here: [https://github.com/eske/seq2seq/](https://github.com/eske/seq2seq/) (master branch).
The configuration files for the APE task are available inside [config/APE17](https://github.com/eske/seq2seq/tree/master/config/APE17).

Alexandre
