### ISSUE TITLE
Some shell does not work.

### ISSUE THREAD

**Issue by guotong1988** [eske/seq2seq#17]
https://github.com/eske/seq2seq/blob/master/config/WMT14/download.sh#L18-L19

We have the original downloaded data:
```
ntst14.en
ntst14.fr
ntst1213.en
ntst1213.fr
```

What is `ntst1213.fr-en` and `ntst14.fr-en`?

@eske Thank you!

**Comment by eske** [comment]
Hello,
The purpose of lines 18 and 19 is to rename `dev/ntst14.en` to `ntst14.fr-en.en`, `dev/ntst1213.en` to `ntst1213.fr-en.en`, and so on. 
Maybe the `rename` command with this syntax does not work for you. You can do:
```
mv dev/ntst14.en ntst14.fr-en.en
mv dev/ntst14.fr ntst14.fr-en.fr
mv dev/ntst1213.en ntst1213.fr-en.en
mv dev/ntst1213.fr ntst1213.fr-en.fr
```

**Comment by guotong1988** [comment]
thank you
