### ISSUE TITLE
Multi-task training

### ISSUE THREAD

**Issue by menamine** [eske/seq2seq#23]
Hi all, 

For the multi-task training, what kind of architecture did you use to accomplish this task? Did you use a separate encoder/decoder for each task, or did you use shared parameters between the encoder and/or the decoder? Could you make available an article about the implemented architecture. 

Than you in advance.

**Comment by eske** [comment]
Hi,
Actually, it depends on your configuration. If you take a look at [LibriSpeech/Multi-Task.yaml](https://github.com/eske/seq2seq/blob/master/config/LibriSpeech/Multi-Task.yaml), you can see that 3 tasks are defined: MT, ASR and AST. AST and ASR share the same encoder (speech.en), and AST and MT share the same decoder (char.fr)
You can find more info about this model in https://arxiv.org/abs/1802.04200.
This sequence to sequence multi-task training approach was proposed in https://arxiv.org/abs/1511.06114

**Comment by menamine** [comment]
Thank you for the answer ^^, it is clear.
Best.
