### ISSUE TITLE
Could you please make the trained model available?

### ISSUE THREAD

**Issue by LeenaShekhar** [eske/seq2seq#9]
Could you please make the trained model available?

**Comment by eske** [comment]
Sorry for the delay. I don't know if you're still interested. I just made the [WMT14](https://drive.google.com/file/d/1XM_76xP5kg8--BvykF3uJdCSYtdLFGX_/view?usp=sharing) and [IWSLT14](https://drive.google.com/file/d/1-RZ-uNaJvn2UuQOmYEjyQl7435CCrrB6/view?usp=sharing) models available (see README).

Alexandre

**Comment by LeenaShekhar** [comment]
Thank you for the models. I forgot to close the thread; sorry about that. 
I will refer to the README.
